version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - echo "Before running tests"
      - python -m pip install --upgrade pip
      - pip install flake8
      - pip install pandas
      - pip install pytest
  build:
    commands:
      - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - echo "Running all unit tests"
      - pytest
      - tar -cf pythonlab1-1_0.tar *
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - pythonlab1-1_0.tar
    - appspec.yml
  discard-paths: yes
